[allowlist]
description = "Allowlist for known false positives"
paths = [
    '''docs/.*''',
    '''tests/.*''',
    '''\.github/.*''',
]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|secret)['"]?\s*[:=]\s*['"]?([a-zA-Z0-9]{32,45})['"]?'''
tags = ["key", "API", "generic"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws[_-]?(?:secret[_-]?)?key[_-]?(?:id)?['"]?\s*[:=]\s*['"]?[A-Za-z0-9/+=]{40}['"]?'''
tags = ["key", "AWS"]

[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''(?i)github[_-]?(?:token|key|secret)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9]{40}['"]?'''
tags = ["key", "GitHub"]

[[rules]]
id = "ssh-private-key"
description = "SSH Private Key"
regex = '''-----BEGIN[_-]?(?:RSA|DSA|EC|OPENSSH)[_-]?PRIVATE[_-]?KEY-----'''
tags = ["key", "SSH"]

[[rules]]
id = "pgp-private-key"
description = "PGP Private Key"
regex = '''-----BEGIN[_-]?PGP[_-]?PRIVATE[_-]?KEY[_-]?BLOCK-----'''
tags = ["key", "PGP"]

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[pboa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32}'''
tags = ["key", "Slack"]

[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z-_]{35}'''
tags = ["key", "Google"]

[[rules]]
id = "google-oauth"
description = "Google OAuth"
regex = '''[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com'''
tags = ["key", "Google"]

[[rules]]
id = "heroku-api-key"
description = "Heroku API Key"
regex = '''[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'''
tags = ["key", "Heroku"]

[[rules]]
id = "mailchimp-api-key"
description = "Mailchimp API Key"
regex = '''[0-9a-f]{32}-us[0-9]{1,2}'''
tags = ["key", "Mailchimp"]

[[rules]]
id = "mailgun-api-key"
description = "Mailgun API Key"
regex = '''key-[0-9a-zA-Z]{32}'''
tags = ["key", "Mailgun"]

[[rules]]
id = "paypal-braintree-access-token"
description = "PayPal Braintree Access Token"
regex = '''access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}'''
tags = ["key", "PayPal"]

[[rules]]
id = "picatic-api-key"
description = "Picatic API Key"
regex = '''sk_live_[0-9a-z]{32}'''
tags = ["key", "Picatic"]

[[rules]]
id = "stripe-api-key"
description = "Stripe API Key"
regex = '''sk_live_[0-9a-zA-Z]{24}'''
tags = ["key", "Stripe"]

[[rules]]
id = "square-access-token"
description = "Square Access Token"
regex = '''sq0atp-[0-9A-Za-z\-_]{22}'''
tags = ["key", "Square"]

[[rules]]
id = "square-oauth-secret"
description = "Square OAuth Secret"
regex = '''sq0csp-[0-9A-Za-z\-_]{43}'''
tags = ["key", "Square"]

[[rules]]
id = "twilio-api-key"
description = "Twilio API Key"
regex = '''SK[0-9a-fA-F]{32}'''
tags = ["key", "Twilio"]

[[rules]]
id = "twitter-access-token"
description = "Twitter Access Token"
regex = '''[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*[1-9][0-9]+-[0-9a-zA-Z]{40}'''
tags = ["key", "Twitter"]

[[rules]]
id = "twitter-oauth"
description = "Twitter OAuth"
regex = '''[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*['"]{1}[a-zA-Z0-9]{35,44}['"]{1}'''
tags = ["key", "Twitter"] 