name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '*.md'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdownlint-cli
        pip install mdformat

    - name: Check markdown formatting
      run: |
        mdformat --check .

    - name: Lint markdown
      run: |
        markdownlint .

    - name: Check for broken links
      run: |
        pip install markdown-link-check
        find . -name \*.md -exec markdown-link-check {} \;

    - name: Validate documentation structure
      run: |
        if [ ! -f README.md ]; then
          echo "README.md is missing"
          exit 1
        fi
        if [ ! -f CONTRIBUTING.md ]; then
          echo "CONTRIBUTING.md is missing"
          exit 1
        fi
        if [ ! -f CODE_OF_CONDUCT.md ]; then
          echo "CODE_OF_CONDUCT.md is missing"
          exit 1
        fi
        if [ ! -f SECURITY.md ]; then
          echo "SECURITY.md is missing"
          exit 1
        fi
        if [ ! -f CHANGELOG.md ]; then
          echo "CHANGELOG.md is missing"
          exit 1
        fi 